# Generated by Django 5.2.8 on 2026-01-28 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorcomercio',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_comercios', to='core.comercio'),
        ),
        migrations.AlterField(
            model_name='proveedorcomercio',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_comercios', to='core.proveedor'),
        ),
    ]
