# Generated by Django 5.2.8 on 2026-01-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proveedorcomercio_comercio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedorcomercio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='proveedorcomercio',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comercio'),
        ),
        migrations.AlterField(
            model_name='proveedorcomercio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], max_length=20),
        ),
    ]
