# Generated by Django 5.2.8 on 2026-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proveedorcomercio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor',
            name='hora_ejecucion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='hora_reintentos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='hora_ejecucion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='hora_reintentos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='proveedorcomercio',
            unique_together={('proveedor', 'comercio')},
        ),
    ]
