# Generated by Django 5.2.8 on 2026-03-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_historicalproveedor_hora_ejecucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='hora_ejecucion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='hora_reintentos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomercio',
            name='hora_ejecucion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomercio',
            name='hora_reintentos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
